---
format: gfm
---

<!-- This document is generated by README.qmd. Please edit that instead! -->

# Modeling scripts

This folder contains the scripts that are used to implement Bayesian models of
the relationship between immune outcomes and titer increase.

* `data-cleaning-models.R`: this script provides the basic data cleaning that
needed to be done across all of the models. More data cleaning will need to
be done within each model script prior to passing the data to Stan, but all
of the common parts are done in this script.
  + The output data set is stored at `data/processed/Model-Data/model-data.Rds`.
  + There is also a lookup table of individual IDs stored at
  `data/processed/Model-Data/it-lut.Rds`.

* `wrapper.R`: this script will eventually run all of the model scripts
with switches to turn on/off particular models. (Note: consider setting
up `targets` instead!! It would probably be easier and better.)

* `modeling-helpers.R`: this script contains helper functions that makes
implementing the models easier.

* Actual modeling scripts: these scripts **fit the models** and get
both **individual level predictions** and **marginal predictions**.
  + `simple-linear-models.R`: fits Bayesian linear models to the relationship
  `outcome ~ normalized_distance` where `outcome` is either prevaccination
  titer, postvaccination titer, or fold change (all on the log scale). Also
  considers three separate models for each: a complete pooling model where
  there are only population parameters for the regression line, a no
  pooling model where each individual has their own parameters for the
  regression line (drawn from a population distribution), and a partial
  pooling approach which merges both of these.

<!-- END OF FILE -->
