---
title: "Untitled"
format: html
---

## Quarto
```{r}


# complete pooling predictions
cp_preds <-
  purrr::map(
    cp_out,
    \(x) get_preds(x, sim_dat, n_samps = N) |>
      clean_list() |>
      dplyr::bind_cols(sim_dat)
  ) |>
  rlang::set_names(split_outcome$outcome) |>
  dplyr::bind_rows(.id = "outcome")

# no pooling predictions
np_preds <-
  purrr::map(
    np_out,
    \(x) get_preds(x, sim_dat, n_samps = N) |>
      clean_list() |>
      dplyr::bind_cols(sim_dat)
  ) |>
  rlang::set_names(split_outcome$outcome) |>
  dplyr::bind_rows(.id = "outcome")

# partial pooling predictions
pp_preds <-
  purrr::map(
    pp_out,
    \(x) get_preds(x, sim_dat, n_samps = N) |>
      clean_list() |>
      dplyr::bind_cols(sim_dat)
  ) |>
  rlang::set_names(split_outcome$outcome) |>
  dplyr::bind_rows(.id = "outcome")
```

```{r}
cp <-
  cp_preds |>
  ggplot() +
  aes(x = x, y = est, group = id, color = outcome) +
  geom_line(alpha = 0.1) +
  facet_wrap(vars(outcome), ncol = 1) +
  zlib::theme_ms() +
  ggtitle("complete pooling\n") +
  labs(
    y = "Counterfactual titer\n", x = ""
  ) +
  guides(color = guide_legend(override.aes = list(alpha = 1))) +
  scale_x_continuous(
    limits = c(0, 1),
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    breaks = seq(-2, 8, 2),
    limits = c(-3, 10),
    expand = c(0, 0)
  )

np <-
  np_preds |>
  ggplot() +
  aes(x = x, y = est, group = id, color = outcome) +
  geom_line(alpha = 0.1) +
  facet_wrap(vars(outcome), ncol = 1) +
  zlib::theme_ms() +
  ggtitle("No pooling\n") +
  labs(y = "", x = "\nSimulated antigenic distance") +
  guides(color = guide_legend(override.aes = list(alpha = 1))) +
  scale_x_continuous(
    limits = c(0, 1),
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    breaks = seq(-2, 8, 2),
    limits = c(-3, 10),
    expand = c(0, 0)
  )

pp <-
  pp_preds |>
  ggplot() +
  aes(x = x, y = est, group = id, color = outcome) +
  geom_line(alpha = 0.1) +
  facet_wrap(vars(outcome), ncol = 1) +
  zlib::theme_ms() +
  ggtitle("Partial pooling\n") +
  labs(y = "", x = "") +
  guides(color = guide_legend(override.aes = list(alpha = 1))) +
  scale_x_continuous(
    limits = c(0, 1),
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    breaks = seq(-2, 8, 2),
    limits = c(-3, 10),
    expand = c(0, 0)
  )

cp + np + pp +
  patchwork::plot_layout(nrow = 1, guides = "collect") &
  theme(legend.position = "bottom")
```
