---
title: "Titer increase censoring with interval bounds"
format: typst
---

Let $x$ be the pre-titer for a given individual and $y$ be the post-titer. We are interested in the fold change, $z = y/x$. We know that for a given titer measurement $T$,
if $T = 5$ in the raw data, then $T \in (0, 10)$ -- that is, we assume the
true HAI measurement is always some positive number, but it could be any
positive number lower than the limit of detection, $10$.

If $T = t \geq 5$ in the raw data, then we know that $T \in [t, t+1)$, because
we only observe certain serial dilutions -- the true maximum serial dilution
which leads to inhibition of agglutination could be anywhere between what
we recorded and the next dilution we actually tested.

So when we consider the fold change or titer increase, we need to take these
censoring limits into account. We have four cases that we need to consider.
In general, we know that sense all of our measurements actually fall into
some interval, there are four numbers we need to consider for every measurement
to determine the censoring bounds. Denoting the recorded measurement as
$T$, we call the lower censoring bound $L_t$ and the upper censoring bound $U_t$.
Then, the set of measurements we need to consider to determine the limits of
$Z = y/x$ where $y \in (L_y, U_y)$ and $x \in (L_x, U_x)$ is
$$
S_z = \left\{\frac{L_y}{L_x},\frac{U_y}{L_x}, \frac{L_y}{U_x}, \frac{U_y}{U_x}\right\}.
$$
Then, we can say that
$$
z \in \left(\min S_z, \max S_z\right).
$$

Note that here we ignore the distinction between open and closed interval bounds
-- they go away and don't matter when we consider the limit
$T \to L_T$ or $T \to U_T$ anyways.

There are four cases to consider in terms of the detection limit.

# Case 1: $y = 5$ and $x=5$

If both $y$ and $x$ are below the limit of detection, then
$y \in (0, \infty)$ and $x \in (0, \infty)$, so
$$
S_z = \left\{\frac{0}{0},\frac{10}{0}, \frac{0}{10}, \frac{10}{10}\right\}.
$$

Of course the form $0/0$ is indeterminate, but it is clear that
$\min S_z \to 0$ and $\max S_z \to \infty$, so $z \in (0, \infty)$. Note that
this is saying that $z$ could be any possible value, which makes sense when
we know that we pretty much don't know anything about the relative values of
$x$ and $y$. These terms will contribute nothing to our data likelihood when
we correct for censoring.

# Case 2: $y = 5$ and $x = a \geq 10$

If $y$ is below the limit of detection and $x$ is above the limit of detection,
then $y \in (0, 10)$ and $x \in [a, a+1)$, so
$$
S_z = \left\{\frac{0}{a},\frac{10}{a}, \frac{0}{a + 1}, \frac{10}{a +1}\right\}.
$$

Therefore, $\min S_z = 0$ and $\max S_z = 10/(a)$, so $z \in (0, 10/a)$.

# Case 3: $y = b \geq 10$ and $x = 5$

If $x$ is below the limit of detection and $y$ is above the limit of detection,
then $y \in [b, b+1)$ and $x \in (0, 10)$, so
$$
S_z = \left\{\frac{b}{0},\frac{b+1}{0}, \frac{b}{10}, \frac{b+1}{10}\right\}.
$$

Therefore, $\min S_z = b/10$ and $\max S_z \to \infty$, so $z \in (b/10, \infty)$.

# Case 4: $y = b \geq 10$ and $x = a \geq 10$

If both $x$ and $y$ are above the limit of detection, then
$y \in [b, b+1)$ and $x \in [a, a+1)$, so
$$
S_z = \left\{\frac{b}{a},\frac{b+1}{a}, \frac{b}{a + 1}, \frac{b+1}{a +1}\right\}.
$$

The extrema of this set are not determinable without knowing more about the
measurements first. So we need to calculate it on the fly.
