---
title: "Proportion Counts for comparing to the continuous method"
author: "Amanda Skarlupka"
date: "`r Sys.Date()`"
output: html_document
---

#Purpose:

The purpose of this code is to quantify the proportions of vaccine responses.

#Prerequisties:

Need to Run:

* ../code/1_cleaning/1_cleaning_code.R
* ../code/1_cleaning/2_pepitope_calculator.Rmd
* ../code/1_cleaning/3_acmap_creation.R
* ../code/1_cleaning/4_acmap_distances.Rmd

# Preparing the analysis:


```{r}
library(cowplot)
library(tidyverse)
d <- readRDS(here::here("data/processed/auc_data_typeA.rds")) %>%
  dplyr::select(-c(distance, prevactiter, postvactiter, method, distance_type, distance_norm)) %>%
  dplyr::distinct() %>%
  base::droplevels()


```
# SD Response

```{r}
#Using averaged Data:
d %>%
  dplyr::filter(dose == "SD") %>%
  dplyr::select(strain_type, vac_short, uniq_id, titerincrease, strain_short) %>%
  dplyr::group_by(strain_type, vac_short) %>%
  dplyr::summarise(ind_n = dplyr::n_distinct(uniq_id),
                   mean_tit = mean(titerincrease), # Mean TI of everyone across every strain
                   total_test = n(),
                   total_strain = dplyr::n_distinct(strain_short),
                   response = sum(titerincrease >= 2),
                   no_response = sum(titerincrease < 2), 
                   pro = response/total_test) %>%
  dplyr::mutate(vac_short = base::substr(vac_short,
                                   start = 6,
                                   stop = nchar(paste(vac_short))),
                across(where(is.numeric), round, digits =3)) %>%
 saveRDS(file = here::here("data/processed/averaged_SD_pro.rds"))
```

```{r SD}
p1 <- d %>%
  dplyr::filter(dose == "SD", strain_type == "H1N1") %>%
  ggplot2::ggplot(aes(x = strain_short,
             y = titerincrease)) +
  ggplot2::geom_jitter(size = 1, shape = ".") +
    ggplot2::geom_boxplot(color = 'red',
                 alpha = 0) +
  ggplot2::geom_hline(yintercept = 2,
             linetype = 'dashed') +
  ggplot2::geom_hline(yintercept = 0,
             linetype = 'dashed') +
  ggplot2::theme_bw() +
  ggplot2::facet_grid(rows = vars(vac_short)) +
  ggplot2::xlab("HAI panel Strain") +
  ggplot2::ylab(latex2exp::TeX("$log_2$(HAI Titer) Increase")) +
  ggplot2::ylim(c(-5, 10)) +
  ggplot2::theme(axis.text.x = element_text(angle = 45, hjust = 1))


p2 <- d %>%
  dplyr::filter(dose == "SD", strain_type == "H3N2") %>%
  ggplot2::ggplot(aes(x = strain_short,
             y = titerincrease)) +
  ggplot2::geom_jitter(size = 1, shape = ".") +
    ggplot2::geom_boxplot(color = 'red',
                 alpha = 0) +
  ggplot2::geom_hline(yintercept = 2,
             linetype = 'dashed') +
  ggplot2::geom_hline(yintercept = 0) +
  ggplot2::theme_bw() +
  ggplot2::facet_grid(rows = vars(vac_short)) +
  ggplot2::xlab("HAI panel Strain") +
  ggplot2::ylab(latex2exp::TeX("$log_2$(HAI Titer) Increase")) +
  ggplot2::ylim(c(-5, 10)) +
  ggplot2::theme(axis.text.x = element_text(angle = 45, hjust = 1))

cowplot::plot_grid(p1, p2,
                   nrow = 2,
                   ncol = 1,
                   rel_heights = c(3, 5),
                   labels = "AUTO") %>%
  cowplot::ggsave2(filename = here::here("results/figures/sd_strain_individual.png"),
          height = 10,
          width = 4,
          scale = 1.5)
```

# SD/HD Response

## By Strain

```{r}
#Using averaged Data:

d %>%
  dplyr::filter(age >= 65) %>%
  dplyr::select(strain_type, vac_short, uniq_id, titerincrease, strain_short, dose) %>%
  dplyr::group_by(strain_type, vac_short, dose) %>%
  dplyr::summarise(ind_n = dplyr::n_distinct(uniq_id),
                   mean_tit = mean(titerincrease), # Mean TI of everyone across every strain
                   total_test = n(),
                   total_strain = dplyr::n_distinct(strain_short),
                   response = sum(titerincrease >= 2),
                   no_response = sum(titerincrease < 2), 
                   pro = response/total_test,
                   check = total_strain*ind_n) %>%
  dplyr::group_by(strain_type, vac_short) %>%
  dplyr::mutate(rel_risk_HD_SD = pro[2]/pro[1],
                mean_ti_diff = mean_tit[2]-mean_tit[1])%>% #Proportion >= 2 of everyone across every strain
  dplyr::ungroup() %>%
  dplyr::mutate(vac_short = base::substr(vac_short,
                                   start = 6,
                                   stop = nchar(paste(vac_short))),
                across(where(is.numeric), round, digits =3)) %>%
  saveRDS(file = here::here("data/processed/averaged_SDHD_pro.rds"))

```


```{r}
p1 <- d %>%
  dplyr::filter(age >= 65, 
                strain_type == "H1N1") %>%
  ggplot2::ggplot(aes(x = strain_short,
             y = titerincrease,
             color = dose)) +
  ggplot2::geom_jitter(size = 1, shape = ".") +
    geom_boxplot(alpha = 0) +
  ggplot2::geom_hline(yintercept = 2,
             linetype = 'dashed') +
  ggplot2::geom_hline(yintercept = 0,
             linetype = 'dashed') +
  ggplot2::theme_bw() +
  ggplot2::facet_grid(rows = vars(vac_short)) +
  ggplot2::labs(color = "Dose") +
  ggplot2::xlab("HAI panel Strain") +
  ggplot2::ylab(latex2exp::TeX("$log_2$(HAI Titer) Increase")) +
  ggplot2::theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(legend.position = "none")

p2 <- d %>%
  dplyr::filter(age >= 65, 
                strain_type == "H3N2") %>%
  ggplot2::ggplot(aes(x = strain_short,
             y = titerincrease,
             color = dose)) +
  ggplot2::geom_jitter(size = 1, shape = ".") +
  ggplot2::geom_boxplot(alpha = 0) +
  ggplot2::geom_hline(yintercept = 2,
             linetype = 'dashed') +
  ggplot2::geom_hline(yintercept = 0) +
  ggplot2::theme_bw() +
  ggplot2::facet_grid(rows = vars(vac_short)) +
  ggplot2::labs(color = "Dose") +
  ggplot2::xlab("HAI panel Strain") +
  ggplot2::ylab(latex2exp::TeX("$log_2$(HAI Titer) Increase")) +
  ggplot2::ylim(c(-5, 10)) +
  ggplot2::theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggplot2::theme(legend.position = "bottom")

cowplot::plot_grid(p1, p2,
                   nrow = 2,
                   ncol = 1,
                   rel_heights = c(3, 5),
                   labels = "AUTO") %>%
  cowplot::ggsave2(filename = here::here("results/figures/sdhd_strain_individual.png"),
          height = 10,
          width = 4,
          scale = 1.5)
```

